-- CreateEnum
CREATE TYPE "MediaCategory" AS ENUM ('PAINTING', 'DRAWING', 'SCULPTURE', 'PRINTMAKING', 'PHOTOGRAPHY', 'VIDEO_ART', 'INSTALLATION', 'CERAMICS', 'TEXTILE_ART', 'MIXED_MEDIA', 'COLLAGE', 'DIGITAL_ART', 'PERFORMANCE_ART', 'SOUND_ART', 'LAND_ART', 'ASSEMBLAGE', 'NEW_MEDIA', 'GLASS_ART', 'BOOK_ART', 'STREET_ART');

-- AlterTable
ALTER TABLE "Collection" ADD COLUMN     "category" "MediaCategory";
